### ISSUE TITLE
Plugin don't work after upgrade from 1.8.4 to 1.8.5

### ISSUE THREAD

**Issue by kostopravby** [MadaMzandu/uisp-ros-plugin#25]
After upgrading I see only "loading please wait". Console output:
Uncaught (in promise) TypeError: Failed to execute 'addAll' on 'Cache': Request failed

Failed to load app from service worker. Falling back to plain <script> tag.
(anonymous) @ VM8386 public.php:90

Also request from initiator: crm/_plugins/ros-plugin/public/panel/flutter_service_worker.js?v=150959289 always in pending state.
![image](https://user-images.githubusercontent.com/29959329/176491243-eab9955e-e800-4fce-9a0f-53467d5885e2.png)

Reinstalling plugin doesn't solve he problem

**Comment by MadaMzandu** [comment]
Hi thanks for the feedback. Assuming that php cli is installed on the ucrm system can you try the following command at the command line and provide output. If all goes well there should be no output.

 php /home/unms/data/ucrm/ucrm/data/plugins/ros-plugin/public.php

**Comment by kostopravby** [comment]
there was no entries in error.log. I'll try to run this command

ср, 29 июн. 2022 г., 20:36 Madalitso Mzandu ***@***.***>:

**Comment by MadaMzandu** [comment]
It sounds like there was a problem during the schema update. You can download a repair script and run it from command line like so

>sudo apt -y install php-cli php-sqlite3
>wget https://github.com/MadaMzandu/uisp-ros-plugin/blob/main/src/includes/ud-repair.php
> php ud-repair.php

**Comment by kostopravby** [comment]
> Hi thanks for the feedback. Assuming that php cli is installed on the ucrm system can you try the following command at the command line and provide output. If all goes well there should be no output.
> 
> php /home/unms/data/ucrm/ucrm/data/plugins/ros-plugin/public.php

No output


> It sounds like there was a problem during the schema update. You can download a repair script and run it from command line like so
> 
> >

I remove plugin, checked that plugin folder doesn't exist and then install plugin again. So this is not problem with database.

**Comment by MadaMzandu** [comment]
What happens if you roll back to 1.8.4?

**Comment by kostopravby** [comment]
with 1.8.4d all OK. uisp version 1.4.4

**Comment by MadaMzandu** [comment]
Are you able to provide anydesk  or team viewer to help debug the problem? If so you can use my public email address, it would be good to identify if there is a bug. Thanks

**Comment by MadaMzandu** [comment]
Further debugging shows version 1.8.5 fails to load if the browser language is not in the currently supported list. A fix has been implemented and the builds have been updated

**Comment by kostopravby** [comment]
great, waiting

**Comment by kostopravby** [comment]
Working

**Comment by MadaMzandu** [comment]
many thanks for you feedback and opening the issue. closing
