### ISSUE TITLE
Error after editing a service

### ISSUE THREAD

**Issue by kikipatton** [MadaMzandu/uisp-ros-plugin#26]
I really like this plugin, being using it on 1.4.3 after I upgraded to 1.4.4 it had issues but anyway, I installed **V 1.8.5** on uisp 1.4.3 and I get this error after editing client's service

So it changes everything on the profile and secret but it does not automatically kick off the session like before
{"status":"failed","error":true,"message":"no such command","duration":0,"data":[]}

**Comment by MadaMzandu** [comment]
thanks for the feedback, will verify the problem and give an update

**Comment by kikipatton** [comment]
Thanks, I have also sent you an email incase you need anydesk

**Comment by MadaMzandu** [comment]
Hi,
No need for a remote session, the bug has been found and fixed. You can download the updated build in the usual locations. I am glad you find the plugin useful and your feedback is invaluable as it makes the plugin better for everyone. Thanks

**Comment by kikipatton** [comment]
Okay, downloading it now

**Comment by kikipatton** [comment]
Thanks man, you the best no error and it works fine
