### ISSUE TITLE
Unable to download created back-up

### ISSUE THREAD

**Issue by kikipatton** [MadaMzandu/uisp-ros-plugin#27]
The download button is there but does'nt start downloading

**Comment by MadaMzandu** [comment]
Thanks for the feedback again, will check and update

**Comment by kikipatton** [comment]
Will appreciate alot

**Comment by MadaMzandu** [comment]
This was indeed a bug caused by a broke dependency. The builds have been updated with the fix. Once again thanks for raising the issue.
