### ISSUE TITLE
Profile removal

### ISSUE THREAD

**Issue by kikipatton** [MadaMzandu/uisp-ros-plugin#28]
For some reason, when you suspend an account, let's say it was under 100 Mbps, it suspends that account but also removes the profile instead of leaving it there for the accounts that are using that profile

**Comment by MadaMzandu** [comment]
Thanks for the update I will look at that

**Comment by kikipatton** [comment]
Okay

**Comment by kikipatton** [comment]
> Thanks for the update I will look at that

Hello, any feedback
