### ISSUE TITLE
PROFILE REMOVAL

### ISSUE THREAD

**Issue by kikipatton** [MadaMzandu/uisp-ros-plugin#29]
When you edit an account from active to suspended, it removes the profile.

**Comment by MadaMzandu** [comment]
Please test version 1.8.7 and let me know

**Comment by kikipatton** [comment]
I have tested it, it has resolved that issue
**BUT**
The option of putting an account in disbaled profile is gone, then under settings you can't put 0 as a rate limit for disblaed users.
Thanks for fixing this issue though, I will see you for the effort

**Comment by MadaMzandu** [comment]
Hi
The profile removal has been removed in the current release and profile creation also been fixed please test and let me know
