### ISSUE TITLE
PPPOE service not working

### ISSUE THREAD

**Issue by kaziglv** [MadaMzandu/uisp-ros-plugin#32]
PPPOE service not working, trying to add pppoe user but it creating DHCP user. Please guide.

**Comment by MadaMzandu** [comment]
The plugin will default to DHCP account if both a MAC address and PPPoE credentials are provided. Try to provide only the PPPoE username and password and see if it creates the pppoe account

**Comment by MadaMzandu** [comment]
Please try to use the latest release, the last release 1.8.7 had a bug with the pppoe profiles.

**Comment by MadaMzandu** [comment]
Great!! No that requires changing the code.
