### ISSUE TITLE
Broken since update to UISP 2.1.38

### ISSUE THREAD

**Issue by afrietaadmin** [MadaMzandu/uisp-ros-plugin#34]
Hi 

Upgraded to UISP 2.1.38 (Early access). There is mention in the release notes [https://community.ui.com/releases/UISP-2-1-38/5c628571-2a22-43fc-9c81-f355addb5919] that PHP has been updated to 8.1. and plugins need to be updated.

The plugin does not communicate with the routers as I no longer see any logins from UISP (user I have created on  the MIkrotiks for this).

I have pulled this out out the webhook endpoint (http://localhost/crm/_plugins/ros-plugin/public.php) and hope this helps:

<br />
<b>Warning</b>:  Undefined property: stdClass::$id in <b>/data/ucrm/data/plugins/ros-plugin/lib/service_base.php</b> on line <b>51</b><br />
{"status":"failed","error":true,"message":"Sqlite3 error: Unable to prepare statement: 1, incomplete input"}

<img width="823" alt="image" src="https://user-images.githubusercontent.com/86049538/229984967-4ea9d057-e9fb-424e-9d4b-536b72bb7f23.png">

{
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "cloudbuild.googleapis.com"
        }
      }
    ]
  }
}

**Comment by MadaMzandu** [comment]
Thanks for opening the issue. Will try to reproduce and find the cause, technically 8.1 should be backward compatible with 7.4 in most respects.

**Comment by MadaMzandu** [comment]
The plugin appears to have no problems running on php 8.1. However the webhooks sent by uisp are not complete and have null values. This why the plugin is not able to provision. Perhaps we should wait for another release, 2.1.38 appears to have a broken webhook feature.

**Comment by MadaMzandu** [comment]
Just to update on this it appears uisp version 2.2.5 has been released the issue has been fixed.

**Comment by afrietaadmin** [comment]
Thank you very much for your reply.

I was going to email you and advise the issue has been resolved. I have
upgraded.

Thanks for your help and support.

Its nice dealing with you.

Regards
Shahin
