### ISSUE TITLE
Exeptions not working as expected

### ISSUE THREAD

**Issue by dhanielsnieto** [MadaMzandu/uisp-ros-plugin#41]
i have the 172.99.185.1 on exeption, but 1 subscriber is automatically getting that ip address for some reason

**Comment by dhanielsnieto** [comment]
I tried using the ip in a system subscriber (not for the customer), and when i provision the customer is getting the same ip, so now i have 2 subscribers with the same ip

**Comment by dhanielsnieto** [comment]
Here's a video of what is happening:

https://www.youtube.com/watch?v=5F3aMYpSATo

**Comment by MadaMzandu** [comment]
Thanks for the feedback, have you upgraded to 2.0.2.4. The ip exclusions should be fixed in that verson.

**Comment by dhanielsnieto** [comment]
Yes, I’m using the latest (2.0.2.4)

**Comment by MadaMzandu** [comment]
Thanks for the update. Try to assign the client a fixed address, then after the fixed address is applied, remove the fixed address and apply. This should release the excluded address, and the plugin will not assign it again.

**Comment by dhanielsnieto** [comment]
it is assigning the ip to another customer, is not excluding it

**Comment by MadaMzandu** [comment]
Ok thanks checking

**Comment by MadaMzandu** [comment]
It looks like the list of exclusions is not completing. Please test 2.0.2.5 and let me know. Thanks

**Comment by dhanielsnieto** [comment]
Now customers have a "unknown" package after update and rebuild.

![image](https://github.com/MadaMzandu/uisp-ros-plugin/assets/50563389/a2cb5fd9-641a-4a7e-8665-446e2d53ea82)

**Comment by MadaMzandu** [comment]
Thats strange, rolling back

**Comment by dhanielsnieto** [comment]
System create packages, then it delete packages, and customers. D:

**Comment by dhanielsnieto** [comment]
The exclusions works, but packages broken

**Comment by MadaMzandu** [comment]
Ok lets try 2.0.2.6 and see if the packages and exclusions work properly

**Comment by dhanielsnieto** [comment]
Great news, everything working as expected, thank you so much!
