### ISSUE TITLE
System updating some customers and packages for no reason, causing disconnect.

### ISSUE THREAD

**Issue by dhanielsnieto** [MadaMzandu/uisp-ros-plugin#42]
Each 1 or 2 minutes aprox. the plugin is entering into the mikrotik and change the package, and then change the customer with no reason.

This is only happening with 2 or 3 customers.

![image](https://github.com/MadaMzandu/uisp-ros-plugin/assets/50563389/2d26e163-6dcb-4a35-ba3a-d20fd3305ade)

**Comment by dhanielsnieto** [comment]
Here's the video of what is goin on:

https://youtu.be/iAWd0djBZfI

**Comment by MadaMzandu** [comment]
Thanks for the update. Can you check the Panel > System > Jobs if there is an entry for one of these customers. Also if possible, check CRM > Settings > Webhook if there is a webhook being sent for the same customers service id.

**Comment by MadaMzandu** [comment]
Checking the code I think this could be caused if crm is reporting "other" events that have nothing to do with plugin. 

I am adding a check to verify that the webhooks. https://github.com/MadaMzandu/uisp-ros-plugin/releases/tag/2.0.2.7.

Please test and let me know.

**Comment by dhanielsnieto** [comment]
Testing in few hours, thank you so much for all your work, I’ll let you know later today

**Comment by dhanielsnieto** [comment]
Everything is working as expected, thank you so much!
