### ISSUE TITLE
IP pool exclusions not work 2.0.2.8

### ISSUE THREAD

**Issue by pashtete** [MadaMzandu/uisp-ros-plugin#44]
hi
already installed last version 2.0.2.8
ip pools configured for router:
 - 10.20.1.0/30
 - 10.20.0.0/24
Settings/General/IP pool exclusions - 10.20.0.1,10.20.1.1

added new customer. came as new dhcp lease - 10.20.0.3
i added MAC and choosed Devices in attributes.
plugin did static lease - 10.20.0.1.
edited static lease back to 10.20.0.3

i thought maybe better rebuild plugin data, after updates.
after that:
10.20.0.3(bound lease) edited to 10.20.1.3. do i have to add broadcast address/all non host addresses from network to ip pool exclusions?
10.20.0.166(waiting lease) edited to 10.20.1.1. MAC/Device added, without Static Lease attribute.

Thank you

**Comment by MadaMzandu** [comment]
Thanks for update will recheck exclusions and update

**Comment by MadaMzandu** [comment]
Have verified two problems, assignment is going past the broadcast address, and actual exclusion is being ignored. Will update when fix is uploaded

**Comment by MadaMzandu** [comment]
https://github.com/MadaMzandu/uisp-ros-plugin/releases/tag/2.0.2.9

Thanks for the feedback. Its been fixed. Exclusions were not being read and assignment was going past the broadcast address.

**Comment by MadaMzandu** [comment]
Closing this issue. Please re-open if still having problems
