### ISSUE TITLE
Where is the "Local address" coming from in profile section

### ISSUE THREAD

**Issue by dhanielsnieto** [MadaMzandu/uisp-ros-plugin#50]
Hello, i hope you're well.
i need to know how to change this ip address, the system automatically uses a created ip but i don't know how to change it.

![image](https://github.com/MadaMzandu/uisp-ros-plugin/assets/50563389/674d7f65-5cae-48d1-89c1-abc92974bfa4)

**Comment by dhanielsnieto** [comment]
i've had to manually change to 10.10.48.1

**Comment by dhanielsnieto** [comment]
but once a customer with thae package is unsuspended the ip comes back to the 192.168....

**Comment by MadaMzandu** [comment]
The plugin will use the first **statically** defined ip address that it finds or it will generate one. If you have a preference for an address just make sure its the first address when you /ip address print

As you probably know the framed address on the routers side of the tunnel does not matter. Personally I prefer to use an address that is not in the customer pool on the router side.

**Comment by MadaMzandu** [comment]
If your router does not have static addresses, just add a bridge and put a /32 on it
