### ISSUE TITLE
Moving service from "Site A " to "Site B", is coming with wrong ip from the "site a"

### ISSUE THREAD

**Issue by dhanielsnieto** [MadaMzandu/uisp-ros-plugin#51]
Moving service from one mikrotik to another, "site a" to "site b", is coming with wrong ip from the "site a"
Example:
"Site A" has ip pool 192.168.1.0/24
"Site B" has ip pool 192.168.4.0/24

Moving the service from the site a with ip 192.168.1.3.
System is creating this service on "Site B" with 192.168.1.3 but this pool is not created or working on "Site B".

**Comment by MadaMzandu** [comment]
Thanks for the feed back. I will look at it and update.

**Comment by dhanielsnieto** [comment]
i also found that if you move from one site to another, the secreet keeps in both

**Comment by MadaMzandu** [comment]
Thanks Dhaniels, this look like a serious problem, I am working on it

**Comment by MadaMzandu** [comment]
Ok this has been fixed. I am surprised it did not come up sooner. I will try to make a new release as soon as possible

**Comment by MadaMzandu** [comment]
https://github.com/MadaMzandu/uisp-ros-plugin/releases/tag/2.0.2.11
That should fix the problem. Please test and let me know.

Thanks

**Comment by dhanielsnieto** [comment]
i'll test today, thank you so much

**Comment by dhanielsnieto** [comment]
Problem has been solved, thank you so much!
