### ISSUE TITLE
Duplicate queues being created - DHCP

### ISSUE THREAD

**Issue by afrietaadmin** [MadaMzandu/uisp-ros-plugin#54]
Hi 

Did a rebuild and I noticed that all NAS boxes are now populated with duplicate queues. Not a major problem but I did have to manually delete the extra queues.

ROS Plugin Version: v2.0.2.11
UISP Version: 2.3.39

Thanks
Shahin

**Comment by MadaMzandu** [comment]
Yes, this could come up when migrating from 1.x. The 2.x tries to identify the actual mikrotik queue id while before it was using the comment to pickup the queues. The 2.x queues are named differently it should be safe to delete the old queues.
