### ISSUE TITLE
ROS Plugin not pulling Company Name from UISP 

### ISSUE THREAD

**Issue by afrietaadmin** [MadaMzandu/uisp-ros-plugin#55]
Hi

Have noticed that ROS Plugin is not naming the queues and DHCP Leases when the customer is a Business/Company. Instead it uses Client <UISP ClientId>.

Just a minor issue.

Thanks

**Comment by MadaMzandu** [comment]
Thanks for picking this up, its supposed to prefer the company name. I will review the code and fix for next release.

**Comment by MadaMzandu** [comment]
The code appears to prefer the company name, but will do some tests to see why this might be happening

**Comment by dhanielsnieto** [comment]
I just realized this error, and it is that when it is a company, it only uses **"5180 - Client-XXXX - XXX"**
![image](https://github.com/MadaMzandu/uisp-ros-plugin/assets/50563389/c00d9922-0def-44a8-9fa4-4e131df118a5)

**Comment by MadaMzandu** [comment]
Thanks for extra feedback. I am working to resolve.

**Comment by MadaMzandu** [comment]
Have reupped version 2.0.2.11 with the fix. Problem is that its not caching company name. 

After applying the fix - settings > cache button,  then rebuild router. There will be a duplicate queue - delete the client-xx queue

**Comment by MadaMzandu** [comment]
This problem is more serious than first thought, also in the plugin's service listing the company name is not showing. also related
if service is suspended a new queue with slightly different name is created.
