### ISSUE TITLE
manifest file is not found

### ISSUE THREAD

**Issue by MetallicJohn** [MadaMzandu/uisp-ros-plugin#57]
when i upload to ucrm, i get the error manifest file is not found in the zip archive

**Comment by MadaMzandu** [comment]
Hi John
This usually means the source code file is being uploaded. The binary file is usually the first file in the asset listing "ros-plugin.zip"

**Comment by MetallicJohn** [comment]
many thanks, i will see you on kofi

**Comment by MadaMzandu** [comment]
Appreciated.
