### ISSUE TITLE
Serious Bug: creating a 1M queue on target 0.0.0.0/0 for archived subscriber

### ISSUE THREAD

**Issue by afrietaadmin** [MadaMzandu/uisp-ros-plugin#58]
<img width="865" alt="Queues created incorrectly 1" src="https://github.com/MadaMzandu/uisp-ros-plugin/assets/86049538/9ab7dccf-c933-466e-a52e-4f25fcde8055">

This had the effect of dropping traffic for my  entire subscriber subscriber base.

I can delete the queue and the moment I reenable the plugin, it will recreate the queue

**Comment by MadaMzandu** [comment]
Ok not a good one. Is the address pool okey? Why no address? I will check it and update you

**Comment by MadaMzandu** [comment]
I still cannot recreate this problem, but I will keep looking at the code, perhaps I will see something.

**Comment by afrietaadmin** [comment]
Hi

Check this

I created a queue using the rest api without specifying the target

[image: image.png]

When you open the specific queue, you can see the target is 0.0.0.0/0

[image: image.png]

And yes it is affecting traffic

[image: image.png]

what you need to ask is why is the code acting upon services where client
is archived and then restored for administrative purposes. UISP only allows
you to look at data when a client is restored. we often remove the IP
address from the IP Address as was the case. Check if your code is creating
a queue with a target unspecified because in the Mikrotik unspecified
defaults to 0.0.0.0/0

hope this helps.

**Comment by MadaMzandu** [comment]
Thanks for the update, now that makes sense. When the client is restored uisp sends a trigger to re-create the account.

I guess the problem here is that the plugin is creating an account when the service has no ip address. I will check and correct.

**Comment by MadaMzandu** [comment]
I have upped version 2.0.2.19 which attempts to skip creating the account if an ip address is not available. I think this should solve the problem

**Comment by afrietaadmin** [comment]
Thanks Bro
