### ISSUE TITLE
Bug on update client speed or delete

### ISSUE THREAD

**Issue by BlackMix** [MadaMzandu/uisp-ros-plugin#60]
Hi,
For some reason when I change the speed plan and synchronize with Mikrotik it always goes to the old speed and doesn't update to the new speed, another thing is when I delete a user the plugin continues sending the deleted user... it seems like it has some cache and it is not updated when editing a user.

I user Router OS 7

**Comment by MadaMzandu** [comment]
Thanks for the feedback, which version of the plugin is running on your system?

**Comment by BlackMix** [comment]
latest version

**Comment by BlackMix** [comment]
Another thing is the possibility of adding a name to the IP pool to get the already saved pool... currently it is not allowed to add a name

**Comment by MadaMzandu** [comment]
> Another thing is the possibility of adding a name to the IP pool to get the already saved pool... currently it is not allowed to add a name

The mikrotik pools are dynamic and can cause the client's ip address to change - nms and crm need the client's address to be a "static" lease, this is why the plugin does not support pool names

**Comment by MadaMzandu** [comment]
> latest version

Ok will check it

**Comment by BlackMix** [comment]
Is there any possibility of you adding the option to select the type of service?
that way you would have more security

![image](https://github.com/MadaMzandu/uisp-ros-plugin/assets/16123328/391f0a70-fe2a-4f09-93dc-77c7fa418377)

![image](https://github.com/MadaMzandu/uisp-ros-plugin/assets/16123328/8caa370a-dfb7-426d-bd8e-7a9df4912c7c)

**Comment by MadaMzandu** [comment]
> Is there any possibility of you adding the option to select the type of service? that way you would have more security
> 
> ![image](https://user-images.githubusercontent.com/16123328/275283298-391f0a70-fe2a-4f09-93dc-77c7fa418377.png)
> 

I am not sure of if there is a situation where this would be helpful. Currently the plugin selects the type of service by the custom attributes specified:

If a valid mac address is provided - it assumes dhcp, if a username is provided it assumes ppp, and if a username and hotspot is enabled then it's a hotspot account.

![image](https://github.com/MadaMzandu/uisp-ros-plugin/assets/59873984/e3efa4bd-8f33-4f2e-bd33-bc8edda606e7)

**Comment by MadaMzandu** [comment]
> latest version
I have done these tests on 2.0.2.19 and found that the results are normal:

1. Archive Client + Delete Client + Sync Router - service is deleted on archive and is not sent again on sync
2. Delete Service + Sync Router - service is deleted on delete and is not sent on sync
3. Edit Service Plan in Plugin - services on plan are updated with new plan settings automatically without sync
4. Edit Service Plan in UISP + Sync Router - services are updated with new plan settings on sync.**

** Editing the service plan in uisp requires manual sync because uisp does not update the plugin

If there is a test you would like me to try just specify it and I will go through it

**Comment by BlackMix** [comment]
When I synchronize the information goes as "any" service, this is not good for good practice, maybe it's because it has "ppp" instead of "pppoe", I'll try synchronizing again, anything I can try to fix, I think which is the information saved in sqlite3 that somehow does not update when I change the information, I need to study the plugin to understand how the synchronization steps are.

but thanks for the answers and trying to simulate my problem, life is too busy hahaha

**Comment by MadaMzandu** [comment]
Yes the plugin is not specifically for pppoe, but any ppp service that you want to sell from a mikrotik
